### ISSUE TITLE
Logging when members leave the server

### ISSUE THREAD

**Issue by leavism** [sfsu-acm/Lovelace#7]
There's a channel called #logging under the Admin category. Guess what we'll use that for 🤔

Have Lovelace send a message to the #logging channel whenever a member leaves our Discord server. The message should be formatted as:

> [USERNAME] has left the server.

You'll probably want to create an alternative Discord account and use that to test this functionality.

**Hint**
- This is an event listener, not a command.
- To save you time because the docs suck, the event you're listening for is called `guildMemberRemove`.
- You will have to write a function that finds the logging channel before you can send a message there. You will have to hard-code it to find the name "logging." This doc might help https://discord.js.org/docs/packages/discord.js/14.15.3/GuildChannelManager:Class#fetch

**Comment by OskoPoland** [comment]
I'd like to try this. I removed the issue from my incorrect pull request and will move it to a new one I am about to make.

**Comment by leavism** [comment]
Don't find the channel via ID. Find the channel via name "logging."
