### ISSUE TITLE
Update contributors in the stats command

### ISSUE THREAD

**Issue by leavism** [sfsu-acm/Lovelace#8]
The author field in the stats command is no longer accurate! Update the field so that:
- The field is now called **Contributors** rather than Author.
- Include everyone's name (Ary, Ria, Trenton, and John) Ask them how they'd like to be referred to.
- Figure out an aesthetic way to list everyone's names. A comma list may suffice, but is there anything else we can try?
- Maybe include a link to their GitHub profile, like how I have my website as a link when someone clicks on my name.

**Comment by riathakker** [comment]
I'd like to try this one.
